// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ComCodeFormReq struct {
	Code *string `form:"code,optional"` // code
}

type ComFilterFormReq struct {
	Filter *string `form:"filter,optional"` // filter
}

type ComIDFormReq struct {
	ID *string `form:"id,optional"` // id
}

type ComIDPathReq struct {
	ID string `path:"id"` // id
}

type ComKvListResp struct {
	Items []*ComKvResp `json:"items"` // list
}

type ComKvResp struct {
	Key   string `json:"key"`   // key
	Value string `json:"value"` // value
}

type ComLoginReq struct {
	UserName string `json:"userName"` // username
	Password string `json:"password"` // password
}

type ComLoginResp struct {
	AccessToken  string `json:"accessToken"`  // accessToken
	AccessExpire int64  `json:"accessExpire"` // accessExpire
	RefreshAfter int64  `json:"refreshAfter"` // refreshAfter
}

type ComPageFormReq struct {
	Page     int     `form:"page"`            // page
	PageSize int     `form:"pageSize"`        // pageSize
	Filter   *string `form:"filter,optional"` // filter
}

type ComSmsLoginReq struct {
	Phone   string `json:"phone"`
	SmsCode string `json:"smsCode"`
}

type ComUserChangePwdReq struct {
	OldPassword string `json:"oldPassword"` // oldPassword
	NewPassword string `json:"newPassword"` // newPassword
}

type ComUserResetPwdReq struct {
	UserID   string `json:"userId"`   // userId
	Password string `json:"password"` // password
}

type DictionaryEditReq struct {
	ID        string `path:"id"`        //ID
	PID       string `json:"pid"`       //父级ID
	DicName   string `json:"dicName"`   //字典名称
	DicCode   string `json:"dicCode"`   //字典编码
	DicDesc   string `json:"dicDesc"`   //字典描述
	DicValue  string `json:"dicValue"`  //字典值
	DicValue2 string `json:"dicValue2"` //字典值2
	DicValue3 string `json:"dicValue3"` //字典值3
	Sort      int    `json:"sort"`      //排序
}

type DictionaryListReq struct {
	Pid      *string `form:"pid,optional"`      //父级ID
	IsEnable *bool   `form:"isEnable,optional"` //是否启用[true:启用;false:禁用]
	Filter   *string `form:"filter,optional"`   //过滤条件
}

type DictionaryListResp struct {
	Items []*DictionaryResp `json:"items"` //列表
}

type DictionaryReq struct {
	PID       string `json:"pid"`       //父级ID
	DicName   string `json:"dicName"`   //字典名称
	DicCode   string `json:"dicCode"`   //字典编码
	DicDesc   string `json:"dicDesc"`   //字典描述
	DicValue  string `json:"dicValue"`  //字典值
	DicValue2 string `json:"dicValue2"` //字典值2
	DicValue3 string `json:"dicValue3"` //字典值3
	Sort      int    `json:"sort"`      //排序
}

type DictionaryResp struct {
	ID        string `json:"id"`        //ID
	PID       string `json:"pid"`       //父级ID
	DicName   string `json:"dicName"`   //字典名称
	DicCode   string `json:"dicCode"`   //字典编码
	DicDesc   string `json:"dicDesc"`   //字典描述
	DicValue  string `json:"dicValue"`  //字典值
	DicValue2 string `json:"dicValue2"` //字典值2
	DicValue3 string `json:"dicValue3"` //字典值3
	Sort      int    `json:"sort"`      //排序
	IsEdit    bool   `json:"isEdit"`    //是否可编辑
	IsEnable  bool   `json:"isEnable"`  //是否启用
	CreatedAt int64  `json:"createdAt"` //创建时间
	UpdatedAt int64  `json:"updatedAt"` //更新时间
}

type MenuEditReq struct {
	ID                   string `path:"id"`                   //ID
	PID                  string `json:"pid"`                  //父级ID
	MenuName             string `json:"menuName"`             //菜单名称
	MenuDesc             string `json:"menuDesc"`             //菜单描述
	MenuIcon             string `json:"menuIcon"`             //菜单图标
	MenuPath             string `json:"menuPath"`             //菜单路径
	MenuType             int    `json:"menuType"`             //菜单类型[1:菜单;2:按钮]
	MenuComponent        string `json:"menuComponent"`        //菜单组件
	IsHideInMenu         bool   `json:"isHideInMenu"`         //是否隐藏菜单[true:隐藏;false:显示]
	IsHideChildrenInMenu bool   `json:"isHideChildrenInMenu"` //是否隐藏子菜单[true:隐藏;false:显示]
	IsHideInBreadcrumb   bool   `json:"isHideInBreadcrumb"`   //是否隐藏面包屑[true:隐藏;false:显示]
	Sort                 int    `json:"sort"`                 //排序
}

type MenuListResp struct {
	Items []*MenuTreeResp `json:"items"` //列表
}

type MenuReq struct {
	PID                  string `json:"pid"`                  //父级ID
	MenuName             string `json:"menuName"`             //菜单名称
	MenuCode             string `json:"menuCode"`             //菜单编码
	MenuDesc             string `json:"menuDesc"`             //菜单描述
	MenuIcon             string `json:"menuIcon"`             //菜单图标
	MenuPath             string `json:"menuPath"`             //菜单路径
	MenuType             int    `json:"menuType"`             //菜单类型[1:菜单;2:按钮]
	MenuComponent        string `json:"menuComponent"`        //菜单组件
	IsHideInMenu         bool   `json:"isHideInMenu"`         //是否隐藏菜单[true:隐藏;false:显示]
	IsHideChildrenInMenu bool   `json:"isHideChildrenInMenu"` //是否隐藏子菜单[true:隐藏;false:显示]
	IsHideInBreadcrumb   bool   `json:"isHideInBreadcrumb"`   //是否隐藏面包屑[true:隐藏;false:显示]
	Sort                 int    `json:"sort"`                 //排序
	IsJoinAdminist       bool   `json:"isJoinAdminist"`       //是否加入管理员菜单[true:是;false:否]
}

type MenuResp struct {
	ID                   string `json:"id"`                   //ID
	PID                  string `json:"pid"`                  //父级ID
	MenuName             string `json:"menuName"`             //菜单名称
	MenuCode             string `json:"menuCode"`             //菜单编码
	MenuDesc             string `json:"menuDesc"`             //菜单描述
	MenuIcon             string `json:"menuIcon"`             //菜单图标
	MenuPath             string `json:"menuPath"`             //菜单路径
	MenuType             int    `json:"menuType"`             //菜单类型[1:菜单;2:按钮]
	MenuComponent        string `json:"menuComponent"`        //菜单组件
	IsHideInMenu         bool   `json:"isHideInMenu"`         //是否隐藏菜单[true:隐藏;false:显示]
	IsHideChildrenInMenu bool   `json:"isHideChildrenInMenu"` //是否隐藏子菜单[true:隐藏;false:显示]
	IsHideInBreadcrumb   bool   `json:"isHideInBreadcrumb"`   //是否隐藏面包屑[true:隐藏;false:显示]
	IsEnable             bool   `json:"isEnable"`             //是否启用[true:启用;false:禁用]
	Sort                 int    `json:"sort"`                 //排序
}

type MenuTreeResp struct {
	MenuResp
	Children []*MenuTreeResp `json:"children"` //子菜单
}

type RoleEditReq struct {
	ID       string `path:"id"`       //ID
	RoleName string `json:"roleName"` //角色名称
	RoleDesc string `json:"roleDesc"` //角色描述
}

type RolePageReq struct {
	ComPageFormReq
	IsEnable        *bool `form:"isEnable,optional"`        //是否启用[true:启用,false:禁用]
	IsSetPermission *bool `form:"isSetPermission,optional"` //是否设置权限[true:已设置,false:未设置]
}

type RolePageResp struct {
	Total int64       `json:"total"` //总数
	Items []*RoleResp `json:"items"` //列表
}

type RoleReq struct {
	RoleName string `json:"roleName"` //角色名称
	RoleCode string `json:"roleCode"` //角色编码
	RoleDesc string `json:"roleDesc"` //角色描述
}

type RoleResp struct {
	ID              string    `json:"id"`              //ID
	RoleName        string    `json:"roleName"`        //角色名称
	RoleCode        string    `json:"roleCode"`        //角色编码
	RoleDesc        string    `json:"roleDesc"`        //角色描述
	IsSetPermission bool      `json:"isSetPermission"` //是否设置权限
	IsAdmin         bool      `json:"isAdmin"`         //是否管理员
	IsEnable        bool      `json:"isEnable"`        //是否启用[true:启用;false:禁用]
	SelectedMenuIds []string  `json:"selectedMenuIds"` //已选菜单ID
	MenuIds         []*string `json:"menuIds"`         //菜单集合ID
	CreatedAt       int64     `json:"createdAt"`       //创建时间
	UpdatedAt       int64     `json:"updatedAt"`       //更新时间
}

type RoleSetPermissionReq struct {
	RoleID          string   `json:"roleId"`
	SelectedMenuIds []string `json:"selectedMenuIds"`
	MenuIds         []string `json:"menuIds"`
}

type UserAvatarEditReq struct {
	Avatar string `json:"avatar"` //头像
}

type UserEditReq struct {
	ID      string   `path:"id"`             //ID
	Name    string   `json:"name"`           //姓名
	Email   *string  `json:"email,optional"` //邮箱
	Phone   *string  `json:"phone,optional"` //手机号
	Avatar  string   `json:"avatar"`         //头像
	RoleIds []string `json:"roleIds"`        //角色ID集合
}

type UserPageReq struct {
	ComPageFormReq
	IsEnable *bool `form:"isEnable,optional"` //是否启用[true:启用,false:禁用]
}

type UserPageResp struct {
	Total int64       `json:"total"`
	Items []*UserResp `json:"items"`
}

type UserReq struct {
	Name     string   `json:"name"`           //姓名
	UserName string   `json:"userName"`       //用户名
	Password string   `json:"password"`       //密码
	Email    *string  `json:"email,optional"` //邮箱
	Phone    *string  `json:"phone,optional"` //手机号
	Avatar   string   `json:"avatar"`         //头像
	RoleIds  []string `json:"roleIds"`        //角色ID集合
}

type UserResp struct {
	ID            string       `json:"id"`             //ID
	Name          string       `json:"name"`           //姓名
	UserName      string       `json:"userName"`       //用户名
	Email         *string      `json:"email,optional"` //邮箱
	Phone         *string      `json:"phone,optional"` //手机号
	Avatar        string       `json:"avatar"`         //头像
	RoleIds       []*string    `json:"roleIds"`        //角色ID集合
	Roles         []*ComKvResp `json:"roles"`          //角色集合
	LastLoginTime string       `json:"lastLoginTime"`  //最后一次登录时间
	IsEnable      bool         `json:"isEnable"`       //是否启用[true:启用,false:禁用]
	IsAdmin       bool         `json:"isAdmin"`        //是否是管理员[true:是,false:否]
	CreatedAt     int64        `json:"createdAt"`      //创建时间
	UpdatedAt     int64        `json:"updatedAt"`      //更新时间
}
